# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
# registries:
#   npm-wefox:
#     type: npm-registry
#     url: https://registry.wefox.io
#     token: ${{secrets.ORG_CORE_NEXUS_NPM_TOKEN}}
#   pypi-wefox:
#     type: python-index
#     url: https://registry.wefox.io/repository/pypi/simple
#     username: ${{ secrets.ORG_CORE_NEXUS_CI_USER }}
#     password: ${{ secrets.ORG_CORE_NEXUS_CI_PWD }}
#     replaces-base: true

updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
  # - package-ecosystem: "npm"
  #   directory: "/"
  #   registries:
  #     - npm-wefox
  #   schedule:
  #     interval: "daily"
  #   allow:
  #     - direct
  # - package-ecosystem: "gradle"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   allow:
  #     - direct
  # - package-ecosystem: "cargo"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   allow:
  #     - direct
  # - package-ecosystem: "pip" # for pip, pip-env, poetry
  #   directory: "/"
  #   registries:
  #     - pypi-wefox
  #   schedule:
  #     interval: "weekly"
  #   allow:
  #     - direct
