---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: linter

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#
#

#############################
# Start the job on all push #
#############################
on:
  push:
  # branches-ignore: ['{{ default_branch }}']
  pull_request:
    branches: ["{{ default_branch }}"]
  workflow_dispatch:

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: '{{#if (eq "v4" superlinter_version ) }}github/super-linter@v4{{else}}docker://ghcr.io/github/super-linter:slim-v4{{/if}}'
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "{{ default_branch }}"
          GITHUB_TOKEN: $\{{ secrets.GITHUB_TOKEN }}
          # LINTER_RULES_PATH: /
          # CSS_FILE_NAME: .stylelintrc.json
          # JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          # VALIDATE_CSS: true
          # VALIDATE_JAVASCRIPT_ES: true
