variables:
  - name: license
    default_value: "Apache-2.0"
    ask: select a license
    select_in_values: |
      {{#jsonnet}}
      local licenses_json = {{ http_get "https://spdx.org/licenses/licenses.json" }};
      local lv = [{label: x.licenseId, value: x} for x in licenses_json.licenses];
      std.sort(lv, keyF=function(x) x.label)
      {{/jsonnet}}

ignores:
  - README.md
  - LICENSE
