name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: setup env
        shell: bash
        run: |
          curl -Lks 'https://github.com/ffizer/ffizer/releases/download/2.8.0/ffizer_2.8.0-x86_64-unknown-linux-gnu.tar.gz' --output ffizer.tar.gz
          tar -xvf ffizer.tar.gz
          ./ffizer --version
      - name: test samples
        shell: bash
        run: |
          # ./ffizer test-samples --source oss_license
          ./test-samples-all.sh
